### PR TITLE
cancel animation frame before requesting another

### PR DESCRIPTION
**Pull request by xsfour**
Moving mouse in every animation frame works better than listening on `onmousemove` event because of the hidden title bar.

### CODE REVIEW

**Comment by mathieudutour** [comment]
I don't really understand why this is supposed to do?

**Comment by xsfour** [comment]
If a `mouseup` event is lost, the `moveWindow` function will be called infinitely because of an uncanceled animation request.

move_window

**Comment by mathieudutour** [comment]
but you code only cancel the frame on the next `mousedown` event so it's not really helpful. Have you seen my proposed solution here: https://github.com/skpm/sketch-module-web-view/issues/100#issuecomment-493785434?

**Comment by xsfour** [comment]
Yes, I saw it and tried it, but found that mouse events are lost only when the draggable area is covered by the **hidden title bar**.
(I guess there is a hidden title bar in the top of the "frameless" window)

However, once the draggable area is covered, the `mousemove` (and `mouseup`) event will be lost as soon as the mouse leaves the area - even if the mouse is still in the window.
In this case, the way to listen to the `mousemove` event is not as good as moving the window every frame because we may lose both `mousemove` and `mouseup` events in the former way but only `mouseup` in the latter.

If we remove the title bar or leave the draggable area away from the title bar, all mouse events will not be lost even if the mouse is outside the window.
But in actual use, it is difficult for us to keep the draggable area away from the title bar.
I tried to remove the title bar in #105, though that work is awful.

Here I am just trying to minimize the impact of the loss of the `mouseup` event.
Regardless of whether there is a modification here, the user can stop moving the window by `click`ing, but without this modification, performance will be affected by the uncanceled animation requests.

**Comment by mathieudutour** [comment]
That seems to work! Merged it here: https://github.com/skpm/sketch-module-web-view/commit/0c755d139abd98f35f845fb7b20f7da041c5fb14

**Pull request closed without merging**
